server:
  port: 8080 || https://ai-personal-finance-manager-backend.onrender.com

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/finance}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expirationMs: 2592000000 # 30 days

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173 || https://aithlete-frontend.vercel.app/ }
