server:
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/finance}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expirationMs: 2592000000 # 30

cors:
  allowed-origins: "http://localhost:5173,https://personal-finance-manager-neon.vercel.app,http://localhost:3000,https://personal-finance-manager-f6sr.onrender.com"
